// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: blink.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecallService_Blink_FullMethodName = "/blink.RecallService/Blink"
)

// RecallServiceClient is the client API for RecallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecallServiceClient interface {
	Blink(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallReply, error)
}

type recallServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecallServiceClient(cc grpc.ClientConnInterface) RecallServiceClient {
	return &recallServiceClient{cc}
}

func (c *recallServiceClient) Blink(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallReply)
	err := c.cc.Invoke(ctx, RecallService_Blink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecallServiceServer is the server API for RecallService service.
// All implementations must embed UnimplementedRecallServiceServer
// for forward compatibility.
type RecallServiceServer interface {
	Blink(context.Context, *RecallRequest) (*RecallReply, error)
	mustEmbedUnimplementedRecallServiceServer()
}

// UnimplementedRecallServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecallServiceServer struct{}

func (UnimplementedRecallServiceServer) Blink(context.Context, *RecallRequest) (*RecallReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Blink not implemented")
}
func (UnimplementedRecallServiceServer) mustEmbedUnimplementedRecallServiceServer() {}
func (UnimplementedRecallServiceServer) testEmbeddedByValue()                       {}

// UnsafeRecallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecallServiceServer will
// result in compilation errors.
type UnsafeRecallServiceServer interface {
	mustEmbedUnimplementedRecallServiceServer()
}

func RegisterRecallServiceServer(s grpc.ServiceRegistrar, srv RecallServiceServer) {
	// If the following call pancis, it indicates UnimplementedRecallServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecallService_ServiceDesc, srv)
}

func _RecallService_Blink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecallServiceServer).Blink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecallService_Blink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecallServiceServer).Blink(ctx, req.(*RecallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecallService_ServiceDesc is the grpc.ServiceDesc for RecallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blink.RecallService",
	HandlerType: (*RecallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Blink",
			Handler:    _RecallService_Blink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blink.proto",
}
