// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: blink.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlinkStatus int32

const (
	BlinkStatus_BLINK_STATUS_UNSPECIFIED BlinkStatus = 0
	BlinkStatus_BLINK_STATUS_ON_COOLDOWN BlinkStatus = 1
	BlinkStatus_BLINK_STATUS_SUCCESS     BlinkStatus = 2 // blinked successfully
	BlinkStatus_BLINK_STATUS_PENDING     BlinkStatus = 3 // attempting to blink
	BlinkStatus_BLINK_STATUS_CRASHED     BlinkStatus = 4 // rnged
	BlinkStatus_BLINK_STATUS_FAILURE     BlinkStatus = 5 // internal error
)

// Enum value maps for BlinkStatus.
var (
	BlinkStatus_name = map[int32]string{
		0: "BLINK_STATUS_UNSPECIFIED",
		1: "BLINK_STATUS_ON_COOLDOWN",
		2: "BLINK_STATUS_SUCCESS",
		3: "BLINK_STATUS_PENDING",
		4: "BLINK_STATUS_CRASHED",
		5: "BLINK_STATUS_FAILURE",
	}
	BlinkStatus_value = map[string]int32{
		"BLINK_STATUS_UNSPECIFIED": 0,
		"BLINK_STATUS_ON_COOLDOWN": 1,
		"BLINK_STATUS_SUCCESS":     2,
		"BLINK_STATUS_PENDING":     3,
		"BLINK_STATUS_CRASHED":     4,
		"BLINK_STATUS_FAILURE":     5,
	}
)

func (x BlinkStatus) Enum() *BlinkStatus {
	p := new(BlinkStatus)
	*p = x
	return p
}

func (x BlinkStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlinkStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blink_proto_enumTypes[0].Descriptor()
}

func (BlinkStatus) Type() protoreflect.EnumType {
	return &file_blink_proto_enumTypes[0]
}

func (x BlinkStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlinkStatus.Descriptor instead.
func (BlinkStatus) EnumDescriptor() ([]byte, []int) {
	return file_blink_proto_rawDescGZIP(), []int{0}
}

type BlinkEvaluationStatus int32

const (
	BlinkEvaluationStatus_BLINK_EVALUATION_STATUS_UNSPECIFIED BlinkEvaluationStatus = 0
	BlinkEvaluationStatus_BLINK_EVALUATION_STATUS_BOOTSTRAP   BlinkEvaluationStatus = 1
	BlinkEvaluationStatus_BLINK_EVALUATION_STATUS_BLINK       BlinkEvaluationStatus = 2
)

// Enum value maps for BlinkEvaluationStatus.
var (
	BlinkEvaluationStatus_name = map[int32]string{
		0: "BLINK_EVALUATION_STATUS_UNSPECIFIED",
		1: "BLINK_EVALUATION_STATUS_BOOTSTRAP",
		2: "BLINK_EVALUATION_STATUS_BLINK",
	}
	BlinkEvaluationStatus_value = map[string]int32{
		"BLINK_EVALUATION_STATUS_UNSPECIFIED": 0,
		"BLINK_EVALUATION_STATUS_BOOTSTRAP":   1,
		"BLINK_EVALUATION_STATUS_BLINK":       2,
	}
)

func (x BlinkEvaluationStatus) Enum() *BlinkEvaluationStatus {
	p := new(BlinkEvaluationStatus)
	*p = x
	return p
}

func (x BlinkEvaluationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlinkEvaluationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blink_proto_enumTypes[1].Descriptor()
}

func (BlinkEvaluationStatus) Type() protoreflect.EnumType {
	return &file_blink_proto_enumTypes[1]
}

func (x BlinkEvaluationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlinkEvaluationStatus.Descriptor instead.
func (BlinkEvaluationStatus) EnumDescriptor() ([]byte, []int) {
	return file_blink_proto_rawDescGZIP(), []int{1}
}

type BlinkEvaluationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlinkEvaluationRequest) Reset() {
	*x = BlinkEvaluationRequest{}
	mi := &file_blink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlinkEvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlinkEvaluationRequest) ProtoMessage() {}

func (x *BlinkEvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlinkEvaluationRequest.ProtoReflect.Descriptor instead.
func (*BlinkEvaluationRequest) Descriptor() ([]byte, []int) {
	return file_blink_proto_rawDescGZIP(), []int{0}
}

func (x *BlinkEvaluationRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type BlinkEvaluationReply struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            BlinkStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=blink.BlinkStatus" json:"status,omitempty"`
	RemainingCooldown float64                `protobuf:"fixed64,2,opt,name=remaining_cooldown,json=remainingCooldown,proto3" json:"remaining_cooldown,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BlinkEvaluationReply) Reset() {
	*x = BlinkEvaluationReply{}
	mi := &file_blink_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlinkEvaluationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlinkEvaluationReply) ProtoMessage() {}

func (x *BlinkEvaluationReply) ProtoReflect() protoreflect.Message {
	mi := &file_blink_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlinkEvaluationReply.ProtoReflect.Descriptor instead.
func (*BlinkEvaluationReply) Descriptor() ([]byte, []int) {
	return file_blink_proto_rawDescGZIP(), []int{1}
}

func (x *BlinkEvaluationReply) GetStatus() BlinkStatus {
	if x != nil {
		return x.Status
	}
	return BlinkStatus_BLINK_STATUS_UNSPECIFIED
}

func (x *BlinkEvaluationReply) GetRemainingCooldown() float64 {
	if x != nil {
		return x.RemainingCooldown
	}
	return 0
}

type BlinkEvaluatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Status        BlinkEvaluationStatus  `protobuf:"varint,2,opt,name=status,proto3,enum=blink.BlinkEvaluationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlinkEvaluatedEvent) Reset() {
	*x = BlinkEvaluatedEvent{}
	mi := &file_blink_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlinkEvaluatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlinkEvaluatedEvent) ProtoMessage() {}

func (x *BlinkEvaluatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_blink_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlinkEvaluatedEvent.ProtoReflect.Descriptor instead.
func (*BlinkEvaluatedEvent) Descriptor() ([]byte, []int) {
	return file_blink_proto_rawDescGZIP(), []int{2}
}

func (x *BlinkEvaluatedEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BlinkEvaluatedEvent) GetStatus() BlinkEvaluationStatus {
	if x != nil {
		return x.Status
	}
	return BlinkEvaluationStatus_BLINK_EVALUATION_STATUS_UNSPECIFIED
}

var File_blink_proto protoreflect.FileDescriptor

var file_blink_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x6c, 0x69, 0x6e, 0x6b, 0x22, 0x28, 0x0a, 0x16, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x71,
	0x0a, 0x14, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x42,
	0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2d, 0x0a, 0x12, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x5f,
	0x63, 0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11,
	0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6f, 0x6c, 0x64, 0x6f, 0x77,
	0x6e, 0x22, 0x5b, 0x0a, 0x13, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x34, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x62, 0x6c, 0x69, 0x6e, 0x6b,
	0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0xb1,
	0x01, 0x0a, 0x0b, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c,
	0x0a, 0x18, 0x42, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1c, 0x0a, 0x18,
	0x42, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x4f, 0x4e, 0x5f,
	0x43, 0x4f, 0x4f, 0x4c, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x42, 0x4c,
	0x49, 0x4e, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x55, 0x43, 0x43, 0x45,
	0x53, 0x53, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x42, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x12, 0x18,
	0x0a, 0x14, 0x42, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43,
	0x52, 0x41, 0x53, 0x48, 0x45, 0x44, 0x10, 0x04, 0x12, 0x18, 0x0a, 0x14, 0x42, 0x4c, 0x49, 0x4e,
	0x4b, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x55, 0x52, 0x45,
	0x10, 0x05, 0x2a, 0x8a, 0x01, 0x0a, 0x15, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x45, 0x76, 0x61, 0x6c,
	0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x23,
	0x42, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x45, 0x56, 0x41, 0x4c, 0x55, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x25, 0x0a, 0x21, 0x42, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x45,
	0x56, 0x41, 0x4c, 0x55, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x42, 0x4f, 0x4f, 0x54, 0x53, 0x54, 0x52, 0x41, 0x50, 0x10, 0x01, 0x12, 0x21, 0x0a, 0x1d,
	0x42, 0x4c, 0x49, 0x4e, 0x4b, 0x5f, 0x45, 0x56, 0x41, 0x4c, 0x55, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x42, 0x4c, 0x49, 0x4e, 0x4b, 0x10, 0x02, 0x32,
	0x5d, 0x0a, 0x0c, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4d, 0x0a, 0x0f, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x6b,
	0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x6b, 0x45,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x14,
	0x5a, 0x12, 0x62, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_blink_proto_rawDescOnce sync.Once
	file_blink_proto_rawDescData []byte
)

func file_blink_proto_rawDescGZIP() []byte {
	file_blink_proto_rawDescOnce.Do(func() {
		file_blink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blink_proto_rawDesc), len(file_blink_proto_rawDesc)))
	})
	return file_blink_proto_rawDescData
}

var file_blink_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_blink_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blink_proto_goTypes = []any{
	(BlinkStatus)(0),               // 0: blink.BlinkStatus
	(BlinkEvaluationStatus)(0),     // 1: blink.BlinkEvaluationStatus
	(*BlinkEvaluationRequest)(nil), // 2: blink.BlinkEvaluationRequest
	(*BlinkEvaluationReply)(nil),   // 3: blink.BlinkEvaluationReply
	(*BlinkEvaluatedEvent)(nil),    // 4: blink.BlinkEvaluatedEvent
}
var file_blink_proto_depIdxs = []int32{
	0, // 0: blink.BlinkEvaluationReply.status:type_name -> blink.BlinkStatus
	1, // 1: blink.BlinkEvaluatedEvent.status:type_name -> blink.BlinkEvaluationStatus
	2, // 2: blink.BlinkService.BlinkEvaluation:input_type -> blink.BlinkEvaluationRequest
	3, // 3: blink.BlinkService.BlinkEvaluation:output_type -> blink.BlinkEvaluationReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blink_proto_init() }
func file_blink_proto_init() {
	if File_blink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blink_proto_rawDesc), len(file_blink_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blink_proto_goTypes,
		DependencyIndexes: file_blink_proto_depIdxs,
		EnumInfos:         file_blink_proto_enumTypes,
		MessageInfos:      file_blink_proto_msgTypes,
	}.Build()
	File_blink_proto = out.File
	file_blink_proto_goTypes = nil
	file_blink_proto_depIdxs = nil
}
