// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: blink.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlinkService_BlinkEvaluation_FullMethodName = "/blink.BlinkService/BlinkEvaluation"
)

// BlinkServiceClient is the client API for BlinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlinkServiceClient interface {
	BlinkEvaluation(ctx context.Context, in *BlinkEvaluationRequest, opts ...grpc.CallOption) (*BlinkEvaluationReply, error)
}

type blinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlinkServiceClient(cc grpc.ClientConnInterface) BlinkServiceClient {
	return &blinkServiceClient{cc}
}

func (c *blinkServiceClient) BlinkEvaluation(ctx context.Context, in *BlinkEvaluationRequest, opts ...grpc.CallOption) (*BlinkEvaluationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlinkEvaluationReply)
	err := c.cc.Invoke(ctx, BlinkService_BlinkEvaluation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlinkServiceServer is the server API for BlinkService service.
// All implementations must embed UnimplementedBlinkServiceServer
// for forward compatibility.
type BlinkServiceServer interface {
	BlinkEvaluation(context.Context, *BlinkEvaluationRequest) (*BlinkEvaluationReply, error)
	mustEmbedUnimplementedBlinkServiceServer()
}

// UnimplementedBlinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlinkServiceServer struct{}

func (UnimplementedBlinkServiceServer) BlinkEvaluation(context.Context, *BlinkEvaluationRequest) (*BlinkEvaluationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BlinkEvaluation not implemented")
}
func (UnimplementedBlinkServiceServer) mustEmbedUnimplementedBlinkServiceServer() {}
func (UnimplementedBlinkServiceServer) testEmbeddedByValue()                      {}

// UnsafeBlinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlinkServiceServer will
// result in compilation errors.
type UnsafeBlinkServiceServer interface {
	mustEmbedUnimplementedBlinkServiceServer()
}

func RegisterBlinkServiceServer(s grpc.ServiceRegistrar, srv BlinkServiceServer) {
	// If the following call pancis, it indicates UnimplementedBlinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlinkService_ServiceDesc, srv)
}

func _BlinkService_BlinkEvaluation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlinkEvaluationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlinkServiceServer).BlinkEvaluation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlinkService_BlinkEvaluation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlinkServiceServer).BlinkEvaluation(ctx, req.(*BlinkEvaluationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlinkService_ServiceDesc is the grpc.ServiceDesc for BlinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blink.BlinkService",
	HandlerType: (*BlinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BlinkEvaluation",
			Handler:    _BlinkService_BlinkEvaluation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blink.proto",
}
